### ISSUE TITLE
表单与流程设计器相关开发

### ISSUE THREAD

**Issue by steedos** [steedos/apps#644]
重要
- [x] 新版流程设计器，设置流程时，开始节点默认的字段都没有选上，这样会导致新建时字段都不可填，应该默认都选上。 #188
- [x] 流程设计器中打开已有流程，修改表单字段公式后点击保存，前台报错 #720
- [x] 审批王表单设计器中，group和table字段没有“必填”选项。 #32

**Comment by steedos** [comment]
请 @sunhaolin 协助搭建环境
